# Generated by Django 3.2.6 on 2021-09-08 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adminname', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cname', models.CharField(max_length=50)),
                ('Cadhar', models.CharField(max_length=50)),
                ('Cemail', models.CharField(max_length=50)),
                ('Caddress', models.CharField(max_length=50)),
                ('Calternatemobilenumber', models.CharField(max_length=50)),
                ('Typeofcustomer', models.CharField(max_length=50)),
                ('Newnumber', models.CharField(max_length=50)),
                ('password', models.CharField(default='admin', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DonglePostpaidplans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('price', models.CharField(max_length=100)),
                ('data', models.CharField(max_length=100)),
                ('offers', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DonglePrepaidplans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('price', models.CharField(max_length=100)),
                ('data', models.CharField(max_length=100)),
                ('validity', models.CharField(max_length=100)),
                ('offers', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Postpaidplans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('price', models.CharField(max_length=100)),
                ('calls', models.CharField(max_length=100)),
                ('data', models.CharField(max_length=100)),
                ('messages', models.CharField(max_length=100)),
                ('offers', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Prepaidplans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('price', models.CharField(max_length=100)),
                ('calls', models.CharField(max_length=100)),
                ('validity', models.CharField(max_length=100)),
                ('data', models.CharField(max_length=100)),
                ('messages', models.CharField(max_length=100)),
                ('offers', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Prepaidplansusage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobilenumber', models.CharField(max_length=10)),
                ('plan', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=50)),
                ('message', models.CharField(max_length=50)),
            ],
        ),
    ]
